### ISSUE TITLE
Expose resolveProxyProvider function as we expose resolveProxyProviders

### ISSUE THREAD

**Issue by jpamorimdev** [Papooch/nestjs-cls#130]
Is it possible to expose `resolveProxyProvider` as we expose `resolveProxyProviders`? It gives us the flexibility of resolving the providers properly when needed.

**Comment by Papooch** [comment]
I had that idea in my mond for a while, too. Do you mean resolving proxy providers individually?

I think it could work if we added an array of proxy provider injection tokens as an array to the `resolveProxProviders` method, which would only resolve those that were supplied. If none are passed, then resolve all that have not been resolved yet. Would that work for your use case?

**Comment by Papooch** [comment]
> it could be useful in some scenarios

I'm not a fan of adding features unless they solve a concrete problem. Let's start with selective resolution of proxy providers only.

**Comment by Papooch** [comment]
Released in `4.3.0`
