### ISSUE TITLE
Docker Error

### ISSUE THREAD

**Issue by shauntrennery** [Papooch/nestjs-cls#137]
Any idea why I'm getting this error within a Docker image?

Nest can't resolve dependencies of the PrismaService (?). Please make sure that the argument ClsService at index [0] is available in the PrismaModule context.

Working perfectly when running locally or once deployed.

**Comment by Papooch** [comment]
Might be because of duplicated `node_modules` inside and outside the image, assuming if you're mounting a volume.

But unless you can show me some more context and/or a minimal reproducible example, it's impossible to tell.

**Comment by Papooch** [comment]
Hey @shauntrennery, were you able to move past this, or are you still stuck?

**Comment by Papooch** [comment]
Okay, I'll leave the issue open for now. When you revisit it, be sure to get back with more details and ideally some reproduction, so I can help you investigate.
