### ISSUE TITLE
How to get a real database transaction in a test environment?

### ISSUE THREAD

**Issue by sam-artuso** [Papooch/nestjs-cls#139]
I'm writing some database integration tests. I'd like to run my queries inside a real database transaction. How to get a real database transaction in a test environment?

**Comment by Papooch** [comment]
I'm not sure I understand what you mean by a test environment.

If you spin up a real database in your test environemnt then you can get a real database transaction in the test application.

Could you be a little more specific?

**Comment by sam-artuso** [comment]
I'm sorry, this is due to a total misunderstanding on my side. Please ignore.
