### ISSUE TITLE
transactional-adapter-pg-promise: where are the default tx options merged with tx-specific options?

### ISSUE THREAD

**Issue by sam-artuso** [Papooch/nestjs-cls#147]
Hi, after version [1.3.0](https://github.com/Papooch/nestjs-cls/releases/tag/%40nestjs-cls%2Ftransactional-adapter-pg-promise%401.3.0) of transactional-adapter-pg-promise the default options seem to no longer be merged in.

I cannot find where this happens in the [source code](https://github.com/Papooch/nestjs-cls/blob/main/packages/transactional-adapters/transactional-adapter-pg-promise/src/lib/transactional-adapter-pg-promise.ts). Is this a bug?

**Comment by sam-artuso** [comment]
Perhaps [here](https://github.com/Papooch/nestjs-cls/blob/main/packages/transactional/src/lib/transaction-host.ts#L134)? Default options are not working for me though. Will try and create a minimal reproducible example as soon as I get a chance.

**Comment by Papooch** [comment]
Hi, I'm sorry, I should've probably let you know.

I moved the feature to the TransactionHost itself, so all adapters can take advantage of it without explicitly implementing the feature.

Please make sure to also update `@nestjs-cls/transactional` to latest version.

**Comment by Papooch** [comment]
@sam-artuso Does it work for you on the latest version?

**Comment by sam-artuso** [comment]
Yes, it does work :)
