### ISSUE TITLE
setup / generateId functions not called in WebSocket Gateway

### ISSUE THREAD

**Issue by sagi-orchid** [Papooch/nestjs-cls#148]
Hi, first of all thanks for this library.

I have an application in which I use your package and it works very well, I use it across many services with `ClsGuard`. I have an issue on my WebSocket gateway, where the `setup` AND the `generateId` functions are not called at all, even though the CLS context is successfully initialized. Here is my config:

```
{
      guard: {
        generateId: false,
        mount: true,
        setup: (cls, ctx) => {
          console.log('***** SETUP *****')
          const reqType = ctx.getType<ContextType | 'rmq'>()
          switch (reqType) {
            case 'rmq': {
              const rmqData = ctx.switchToRpc().getData()

              Object.entries(rmqData?.ctx ?? {}).forEach(([key, val]) => {
                cls.set(key, val)
              })

              break
            }

            case 'rpc': {
              const rpcData = ctx.switchToRpc().getData()

              Object.entries(rpcData?.ctx ?? {}).forEach(([key, val]) => {
                cls.set(key, val)
              })

              break
            }

            case 'http': {
              const req = ctx.switchToHttp().getRequest()
              const organizationIdHeaderVal = req.headers[ORGANIZATION_ID_HEADER_NAME]
              const agentIdHeaderVal = req.headers[AGENT_ID_HEADER_NAME]

              cls.set(ORGANIZATION_ID_CTX_KEY, organizationIdHeaderVal)
              cls.set(AGENT_ID_CTX_KEY, agentIdHeaderVal)
            }
          }
        },
        idGenerator: ctx => {
          console.log('***** ID GEN *****')
          const reqType = ctx.getType<ContextType | 'rmq'>()

          const generateCorrelationId = () => {
            const correlationId = uuidv4()
            logger.debug(`generating new correlation id: ${correlationId}`)
            return correlationId
          }

          logger.debug(`${reqType} request, getting correlation id`)
          let correlationId: string | undefined
          switch (reqType) {
            case 'rmq': {
              const rmqContext = ctx.switchToRpc().getContext()

              correlationId = rmqContext.properties.correlationId
              break
            }

            case 'http': {
              const req = ctx.switchToHttp().getRequest<Request>()
              const correlationIdHeaderVal = req.headers[CORRELATION_ID_HEADER_NAME]

              if (Array.isArray(correlationIdHeaderVal)) {
                correlationId = correlationIdHeaderVal[0]
              } else {
                correlationId = correlationIdHeaderVal
              }

              break
            }

            case 'rpc': {
              const rpcData = ctx.switchToRpc().getData()
              correlationId = rpcData?.ctx?.correlationId
              break
            }

            case 'ws': {
              const message = ctx.switchToWs().getData()
              correlationId = message?.id
              break
            }
          }

          return correlationId ?? generateCorrelationId()
        },
      },
    }
```

Also, this is how I use the guard in my gateway:
```
@UseGuards(ClsGuard, AgentWsGuard)
@WebSocketGateway<ServerOptions>()
export class AgentsGateway implements OnGatewayConnection, OnGatewayInit {}
```

I am well aware that it shouldn't work on handleConnection. When I send a message after handleConnection, none of the console.logs are called. Furthermore, in my other guard `AgentWsGuard`, I set some context using the clsService successfully, which means its successfully initialized.

Any help / direction would be much appreciated.
Thanks!

**Comment by Papooch** [comment]
I don't think the context is getting initialized by the same guard in which the `setup` doesn't get triggered.

What I suspect is happening is that the context is leaking from some other guard execution (since it uses `AsyncLocalStorage#enter()` that _can_ leak, which is usually not a problem unless the leaked context is not overriden by a new one). 

Are you able to create a minimal reproduction that demonstrates the issue, so I can investigate on my end?

**Comment by Papooch** [comment]
You can use an env variabe `DEBUG=true`, which causes Nest to print more debug information during bootstrap.

To further investigate, you could swap the `ClsGuard` for a custom guard which injects `ClsService` and executes `cls.enterWith()` together with some logs to see if it actually gets triggered.

**Comment by sagi-orchid** [comment]
@Papooch Thanks for the tip! I created my own guard and printed CLS_GUARD_OPTIONS, and I found out that the ClsModule was indeed loaded elsewhere, and while not being exported it was set with `global: true` and no config. Removing this instance of ClsModule fixed the issue, and everything works well now.

Thank you for your help :)
