### ISSUE TITLE
Improve type inference and type safety

### ISSUE THREAD

**Issue by micalevisk** [Papooch/nestjs-cls#15]
Instead of:

https://github.com/Papooch/nestjs-cls/blob/f8bc850b3836405fd166ad8e851efdd851c4d55d/src/lib/cls.service.ts#L15

https://github.com/Papooch/nestjs-cls/blob/f8bc850b3836405fd166ad8e851efdd851c4d55d/src/lib/cls.service.ts#L30

we could have this:

```ts
/**
 * Evaluates to `true` if `T` is `any`. `false` otherwise.
 * (c) https://stackoverflow.com/a/68633327/5290447
 */
type IsAny<T> = (
    unknown extends T
    ? [keyof T] extends [never] ? false : true
    : false
);

class ClsService<S extends Record<string, any> = Record<string, any>> {
  // ...

  set<T extends S[K] = any, K extends keyof S = keyof S>(key: K, value: T) {}

  // ...

  get<T = any, K extends keyof S = string>(key: K):
  IsAny<T> extends true
  ? keyof S extends K 
      ? undefined
      : S[K]
  : T
  //
  {}
}
```

Then we will get this:

![image](https://user-images.githubusercontent.com/13461315/149674190-27f5ecb6-48a9-4fde-8264-88167dc96b5b.png)

![image](https://user-images.githubusercontent.com/13461315/149670640-270dc7f2-0662-4e75-9898-f9fd33a9d39c.png)

One thing about my solution is that `clsService.get<foo>('valid')` will always give the type `foo`. I don't know if this is good or not, tbh. I've tried to implement a way on checking if `foo` is assignable to `S['valid']` but didn't succeed.

---

Also, we can't have non-string values as a key on `ClsService#set` and `ClsService#get`, which I think is expected due to the `S = Record<string, any>`, but in the current version this can be bypassed.

**Comment by Papooch** [comment]
Yeah, I admit that I half assed the types to roll out a working solution quickly (and most of it is a remnant of `cls-hooked` that I used originally).

The goal is to make it possible to create an interface for the context:

```ts
interface IStore {
   tenantId: string
   user: {
     name: string,
     age: number,
   }
}
```

inject the ClsService like this:

```ts
constructor(private readonly cls: ClsService<IStore>)
// this is great, since we still don't need `@Inject` even though it's a generic
// the generic gets erased, but the ClsService type is still emitted to the metadata
```
and then get type inference and autocomplete for the (nested) keys 

```ts
cls.set('user.name', 20); // -> error
cls.get('user'); // type: { name: string;  age: number }
cls.get('user.age'); // type: number
cls.get('tenantId');  // type: string
```

This is currently possible with 

```ts
cls.getStore().user.name;
cls.getStore().tenantId;
```

but that is not well documented.

I must definitely revisit it, but you are welcome to create a PR that adresses this.

Since it is a breaking change, we'll need to bump the major version.

**Comment by micalevisk** [comment]
oh I forgot about the nested keys one.

**Comment by Papooch** [comment]
I have the typing ready in the linked PR. I'l stitch it together with the rest of the code and write some tests when I have time.

**Comment by joebowbeer** [comment]
@Papooch Speaking of types, I noticed that the `setup` function's `req` parameter is being typed as the built-in Fetch API `Request`, which is not the `Request` from `express` that it probably is, or the `any` type provided by the Nest.js middleware interface:

https://github.com/nestjs/nest/blob/master/packages/common/interfaces/middleware/nest-middleware.interface.ts

**Comment by svanda-navisys** [comment]
@joebowbeer I assumed that both express and fastify extend the built in Node's Request object, and since you still need to type it manually, it would at least complain if the type was incompatible.

That was my reasoning for using the built in base type, but since nest might actually support other libs, `any` type would be more future proof.

**Comment by joebowbeer** [comment]
In vscode, Request defaults to some built-in type from `lib.dom`, which results in lots of head scratching if I forget to import Request from express.

**Comment by Papooch** [comment]
From the deleted message that comes before joe's answer as I accidentally used my work account.
> I assumed that both express and fastify extend the built in Node's Request object, and since you still need to type it manually, it would at least complain if the type was incompatible.

> That was my reasoning for using the built in base type, but since nest might actually support other libs, any type would be more future proof:

As for the `lib.dom` problem: that should not even be abailable in a backend project, make sure to put `types: ["node"]` in your tsconfig. But I'll definitely revisit the types, thanks for the heads up!
