### ISSUE TITLE
Support for Drizzle ORM

### ISSUE THREAD

**Issue by herenickname** [Papooch/nestjs-cls#155]
Drizzle is an ORM/QueryBuilder that is gaining popularity, I would love to see support for it in your library. Thank you!

**Comment by Papooch** [comment]
Would you like to try and contribute with a Drizzle adapter?

**Comment by herenickname** [comment]
> Would you like to try and contribute with a Drizzle adapter?

I'll give it a try in the next few days, but I don't think I'll get anything bearable out of it

**Comment by lampsbr** [comment]
I'm +1 noob that loves your adapters, want to try drizzle but won't go that path before an adapter is available =D

**Comment by fjanicki** [comment]
I created one for my project, once I tested it fully I can do a PR

**Comment by fjanicki** [comment]
Here's a first PR, it's still missing the tests. I'll try to add them later this week

https://github.com/Papooch/nestjs-cls/pull/179

**Comment by Papooch** [comment]
The [Drizzle adapter](https://papooch.github.io/nestjs-cls/plugins/available-plugins/transactional/drizzle-orm-adapter) was just released.
