### ISSUE TITLE
Nest can't resolve dependencies of the ClsModule (?, ModuleRef). Please make sure that the argument HttpAdapterHost at index [0] is available in the ClsModule context. (Using PNPM)

### ISSUE THREAD

**Issue by RabahZeineddine** [Papooch/nestjs-cls#163]
Updating nestjs/core to `10.3.10` causes this error
```
Nest can't resolve dependencies of the ClsModule (?, ModuleRef). Please make sure that the argument HttpAdapterHost at index [0] is available in the ClsModule context.

Potential solutions:
- Is ClsModule a valid NestJS module?
- If HttpAdapterHost is a provider, is it part of the current ClsModule?
- If HttpAdapterHost is exported from a separate @Module, is that module imported within ClsModule?
  @Module({
    imports: [ /* the Module containing HttpAdapterHost */ ]
  })

Error: Nest can't resolve dependencies of the ClsModule (?, ModuleRef). Please make sure that the argument HttpAdapterHost at index [0] is available in the ClsModule context.

Potential solutions:
- Is ClsModule a valid NestJS module?
- If HttpAdapterHost is a provider, is it part of the current ClsModule?
- If HttpAdapterHost is exported from a separate @Module, is that module imported within ClsModule?
  @Module({
    imports: [ /* the Module containing HttpAdapterHost */ ]
  })

```

Pinning the version to `10.3.8` fix the problem.

**Comment by micalevisk** [comment]
I guess that this has to do with having multiple occurrences of `@nestjs/core` packages loaded into your app

**Comment by Papooch** [comment]
Please see issues #151 and #77. As @micalevisk said, the error is probably caused by version mismatch between the `@nestjs/*` packages.

**Comment by RabahZeineddine** [comment]
@micalevisk i tried removing the `node_modules` and the `pnpm-lock.yaml` and installing it again and it didn't work, 

also did the override to pin the version for peer deps and didn't work..

@Papooch  check my package.json `@nesths/*` versions..
```json
    "@nestjs/common": "10.3.10",
    "@nestjs/core": "10.3.10",
    "@nestjs/platform-express": "10.3.10",
```

**Comment by micalevisk** [comment]
@RabahZeineddine Can you try it out with NPM instead?

**Comment by RabahZeineddine** [comment]
@micalevisk it seems to work with NPM, i removed the node_modules and the lock file and installed using npm.. 
How can we fix it with PNPM? i can't change the repos that we have to use npm :/

**Comment by micalevisk** [comment]
> How can we fix it with PNPM? 

I don't use PNPM often so I'm not sure about it. Can't tell if this is something with `@nestjs/*` packages or a bug in PNPM

**Comment by Papooch** [comment]
Could you create a minimal reproducible example?

I can't tell you whether it's a problem with this library, Nest, pnpm, or combination thereof, and I have myself never used `pnpm` before (save for using it to install dependencies in other people's projects), so I can't promise you I will solve anything, but it would be great to have a reference that we can try to debug locally

**Comment by Papooch** [comment]
@RabahZeineddine Are you by chance using pnpm workspaces? There's [this section in the NestJS docs](https://docs.nestjs.com/faq/common-errors#cannot-resolve-dependency-error) which talks about a special setting for `pnpm`:

> For pnpm Workspaces, set `@nestjs/core` as a `peerDependencies` in your other module and "dependenciesMeta": `{"other-module-name": {"injected": true}}` in the app package.json where the module is imported

**Comment by RabahZeineddine** [comment]
@Papooch we use pnpm workspaces.. we a have a log package that includes nestjs-cls, i just added the dependenciesMeta and it worked! Thank you!! 🚀
