### ISSUE TITLE
mongoose adapter support Propagation.NotSupported mode

### ISSUE THREAD

**Issue by GO-DIE** [Papooch/nestjs-cls#165]
Supports Propagation.NotSupported mode by setting the {session: null} option

**Comment by Papooch** [comment]
I assume you're referring to [this section of the docs](https://papooch.github.io/nestjs-cls/plugins/available-plugins/transactional/mongoose-adapter#considerations) about using the mongoose adapter with their built-in AsyncLocalStorage support.

But I have no idea what you're trying to say. Is that a question or a feature request?

**Comment by Papooch** [comment]
Hey @GO-DIE, could you clarify what you meant by the issue? Otherwise I'm going to close it as invalid for a lack of info.

**Comment by Papooch** [comment]
Closing for lack of clarification
