### ISSUE TITLE
Issue to configure knexInstanceToken in NestJS

### ISSUE THREAD

**Issue by ClaraGr** [Papooch/nestjs-cls#188]
Hello!

I'm encountering an issue to init Cls in my NestJS project.

I'm using Knex and it doesn't seems to export any token I can use in the `knexInstanceToken` parameter of the `TransactionalAdapterKnex`.

```
@Module({
  imports: [
    DatabaseModule,
    ClsModule.forRoot({
      plugins: [
        new ClsPluginTransactional({
          imports: [DatabaseModule],
          adapter: new TransactionalAdapterKnex({
            knexInstanceToken: KNEX_TOKEN, // <= what token do I use?
          }),
        }),
      ],
    }),
  ],
  ...
})
export class NotificationsModule {}
```

I tried multiple solutions, like creating a custom token

`export const KNEX_TOKEN = Symbol('KnexInstance')`

and link it to the KnexInstance I'm configuring in my DatabaseModule

```
@Global()
@Module({
  imports: [
    KnexModule.forRoot({
      config: {
        client: process.env.DATABASE_CLIENT || 'pg',
        connection: {
          host: process.env.DATABASE_HOST || 'localhost',
          user: process.env.DATABASE_USER,
          password: process.env.DATABASE_PASSWORD,
          database: process.env.DATABASE_NAME,
        },
      },
    }),
  ],
  providers: [
    {
      provide: KNEX_TOKEN, // custom token
      useFactory: (knexInstance = knex) => knexInstance, // Trying to link
    },
  ],
  exports: [KNEX_TOKEN], // Export to use in my NotificationsModule
})
export class DatabaseModule {}
```

But it seems that the KnexInstance linked to the custom token isn't the one I've configured above because when I run my app, I get a SQLite error but my config use PostgreSQL.

How I am supposed to configure the ClsPlugin, specifically, what token should I set in the `knexInstanceToken` parameter?

Thanks a lot

**Comment by Papooch** [comment]
It seems you're using some 3rd party Knex wrapper for NestJS. That library uses some injection token to provide the Knex instance - that is the token you need to use for `knexInstanceToken`.

In order for me to help you further, you'll need to tell me which library is that.

**Comment by ClaraGr** [comment]
You're right, I'm using `nest-knexjs`.

In my DatabaseModule I use `import { KnexModule } from 'nest-knexjs'` and configure it with `KnexModule.forRoot({...myConfiguration})`.

Then in my repositories I only have to inject Knex in my constructor like this
```
constructor(
    @InjectConnection() private readonly knex: Knex,
    ...
  ) {}
```

And use Knex in my functions like this
```
const result = await this.knex('tableName as table')
      .select(
        'tableName.id as id',
        ...
      )
```

Thanks a lot

**Comment by Papooch** [comment]
Thanks, after looking at the [library's code](https://github.com/svtslv/nestjs-knex/blob/master/src/knex.decorators.ts), you can see that `InjectConnection` is defined as 
```ts
export const InjectConnection = InjectKnex;
```

while `InjectKnex` is

```ts
export const InjectKnex = (connection?: string) => {
  return Inject(getKnexConnectionToken(connection));
};
```

So the injection toke we're after is `getKnexConnectionToken(connection)`.

The `connection` parameter seems to be an optional connection name, which you can omit if you don't use named connections.

This means, you should be able to set up the transactional plugin like this:

```ts
new ClsPluginTransactional({
  imports: [DatabaseModule],
  adapter: new TransactionalAdapterKnex({
    knexInstanceToken: getKnexConnectionToken(), // <= here
  }),
}),
```
