### ISSUE TITLE
@Transactional on an endpoint and an event handler colliding

### ISSUE THREAD

**Issue by stefda** [Papooch/nestjs-cls#189]
I wrote a custom transactional adapter for pg pool client, and it works really well. Until a decorated event handler is called as a side effect of an endpoint that is also decorated as Transactional.

My use case is fairly simple, I think, and I wonder if I've done something wrong along implementing the custom adapter, or this is simply a case that CLS can't support because it only provides one context instance across request and any side effect processing.

User controller adds a user withing transaction context, then emits "userAdded" event that gets picked up by an event processor, and that should ideally do further updates in the database within another transaction context.

What I find instead is that the call to the `onUserAdded` is actually _not_ within a transaction context with the tx.isTransactionActive() returning false. If I remove the decorator on the controller endpoint, the onUserAdded does execute within active transaction as expected.

This makes me think that both methods share the same ALS instance, the "is transaction active" flag is set to false upon existing the endpoint and therefore the host doesn't provide the client in subsequence calls.

Can you discuss if this use case should be supported, and if so, where I'm making a mistake?

```typescript
// database.module.ts, somewhere in imports
ClsModule.forRoot({
  plugins: [
    new ClsPluginTransactional({
      imports: [PostgresModule.forRoot(options)],
      adapter: new PostgresTransactionalAdapter({ dbInstanceToken: Pool }),
    }),
  ],
  global: true,
  middleware: { mount: true },
})

// user.controller.ts
class UserController {

  constructor(
    private eventEmitter: EventEmitter2,
    private userRepository: UserRepository,
  ) {}
  
  @Post()
  @Transactional()
  public async addUser() {
    await this.userRepository.add(...);
    this.eventEmitter.emit('userAdded');
    return 'OK';
  }
}

// event.processor.ts
class EventProcessor {

  constructor(
    private eventEmitter: EventEmitter2,
    private userRepository: UserRepository,
  ) {}

  @OnEvent('userAdded')
  @Transactional()
  public onUserAdded() {
    // some processing logic
    await this.userRepository.update(...);
  }
}
```

**Comment by Papooch** [comment]
> This makes me think that both methods share the same ALS instance, the "is transaction active" flag is set to false upon existing the endpoint and therefore the host doesn't provide the client in subsequence calls.

Yes, you are correct that the entire promise chain shares the same ALS context - and that includes triggered event handlers.

The default [transaction propagation mode](https://papooch.github.io/nestjs-cls/plugins/available-plugins/transactional#transaction-propagation) is `Required`, which means the nested `@Transactional` decorators try to re-use the existing transaction (and by extension the same ALS context).

A transaction is _started_ as soon as a method with the `@Transactional` decorator is called, and is committed as soon as it finishes, that means the order of operations in your example is as follows:

0) Endpoint called
0) ALS context is initialized
0) A **transaction that wraps the controller begins** and the method starts executing
0) Event is emitted
0) Event handler is synchronously called and nested `@Transactional` decorator is executed
We are still in the context of an active transaction, so it is reused and no nested context is created
0) A promise for the event handler is scheduled and the execution returns to the controller
0) The **controller returns and the transaction is committed**
0) Then the event handler continues executing, but the transaction had already finished.

You could potentially "fix" that by using a different propagation mode, like `RequiresNew` (_Create a new transaction even if one already exists. The new transaction is committed independently of the existing one_), which always creates a new ALS context.

But the most important thing to keep in mind is, again, that a _transaction is started as soon as a method with the `@Transactional` decorator is called, and is committed as soon as it finishes_, so you would be always starting a committing an _empty_ transaction.

---

A little bit of theory now:

A transaction is a _synchronous_ and _atomic_ operation over a database that has well defined entry and exit points, it does not mix well with _asynchronous_ events, which can start and finish _whenever_ after an event is produced.

I see you're trying to implement "hooks" of some kind - you add the user and return to the client, so it expects that the user to have been added. But then you want to continue using the same transaction to update something. What if that update fails? The client will falsely believe that it had added the user, but a failing transaction could have rolled that change back. I'm pretty sure you don't want that behavior.

Or, you do just want the client to start the operation and don't care about the result?

You have to chose - do you need transactional or eventual consistency? (ACID vs BASE)

If you _need_ everything to run within a transaction, then either:
1) do not use events, just regular method calls and _await_ everything
2) if you _do_ use events, await them _synchronously_ via `await this.eventEmitter.emitAsync` to wait for their completion.


If you _don't need_ to run everything within a transaction, but still need eventual consistency, use an Outbox Pattern to transactionally persist messages (so they're not lost on app crash) and then consume them later in a different transaction. (this is out of scope of the question)

**Comment by stefda** [comment]
Thanks for the write up, makes a lot of sense. I have to choose a different approach altogether to implement my use case.

I've been thinking about this a bit more and though I agree with what you wrote, there's still an element of surprise in the current implementation. But I'd attribute it to the error message rather than the design choice.

Since I decorate my even handler with a @Transactional decorator, I (naively) expect the code within that method run in an active transaction. The fact that another overlapping transaction context commited the transaction before it reaches the end is understanable, but it might take some time to figure out that you're doing something you shouldn't. A clear error message along the lines of "another transaction already commited" or something would make for a better DX.

Alternative design choice could be to use some sort of a transaction counter that clearly tracks fully nested transactions and only commits once the counter draws back to zero.

Neither of these solve my specific use case but I thought I'd share them anyway.

**Comment by Papooch** [comment]
I agree that it might be unexpected, but at the same time, I think that creating an elaborate solution with nested transaction counting would do mor harm than good.

Especially since you could easily accidentally create a floating promise which holds the transaction open and then spend countless hours figuring out why your parent transaction did not commit.

An error mesage about the transaction commiting might be helpful though. I'll investigate it further. I think it should be possible to delegate this to the underlying database library.

The issue right now that, by default, the same CLS context is used for nested transactions, so it can be cleared from the parent without the child knowing. If, instead, we create a copy of the context, then the child will still hold a reference to the original transaction and it should throw an appropriate error when trying to use it after commit.
