### ISSUE TITLE
Factory Proxy Providers doesn't work

### ISSUE THREAD

**Issue by kkkstars** [Papooch/nestjs-cls#48]
Hi:
I use Factory Proxy Providers , tenant database connection example.
The provide  "TENANT_CONNECTION" unavailable in my context.
Could you give some more detail with tenant database connection example, like Quick Start example？
Where to use ClsModule.forFeature？
Use ClsModule.forFeature or ClsModule.forFeatureAsync? ClsModule.forFeature 'provide' argument ERROR

Thank you

**Comment by Papooch** [comment]
Here's the tests for the feature: https://github.com/Papooch/nestjs-cls/blob/main/test/proxy-providers/proxy-providers.spec.ts
Could you share a reproduction I could look into?

Keep in mind that the provider must be available in the context of the module in which you're using it, so If you define the proxy provider in one module (Module A) and use it in another (Module B), you might have to _export_ the `ClsModule` from that module (Module A) (https://docs.nestjs.com/modules#module-re-exporting) to make the proxy provider available in the other (Module B).

**Comment by kkkstars** [comment]
thank you, i will try.

**Comment by Papooch** [comment]
@kkkstars have you resolved your issue?
