### ISSUE TITLE
Add ClsInterceptor to avoid having to use enterWith with GraphQL

### ISSUE THREAD

**Issue by andreialecu** [Papooch/nestjs-cls#5]
Hey there, just came across this library while investigating my own issues with `AsyncLocalStorage` losing context inside graphql interceptors.

I'm not (yet) using this library, I have a custom implementation, but I wanted to mention that I eventually got it working via this pattern in the interceptor:

```ts
  intercept(...) {
    return new Observable((observer) => {
      storage.run(myContext, () => {
        next
          .handle()
          .pipe(...)
          .subscribe({
            next: (res) => observer.next(res),
            error: (error) => observer.error(error),
            complete: () => observer.complete(),
          });
      });
    });
  }
```

Seems that wrapping the return in a cold observable is necessary, but this is all that I needed to do.

With this I can use `run` instead of `enterWith`, which I noticed was mentioned as a caveat in the readme about not being supported.

**Comment by Papooch** [comment]
Huh, that's very interesting, I'm going to look into it. I might add this as an alternative solution if you don't mind. Though setting up context in an interceptor would still make it unavailable in guards (which is where I'm mainly using it in my project) and I suspect this trick wouldn't be possible in a guard..
