### ISSUE TITLE
Cls middleware is not triggered in all routes

### ISSUE THREAD

**Issue by alexphamhp** [Papooch/nestjs-cls#67]
I just got this weird error when use your library in Nestjs
I set up it in my AppModule like below :
```
  @Module({
    imports: [
      ClsModule.forRoot({
        global: true,
        middleware: {
          mount: true,
          generateId: true,
          idGenerator: (req: Request) =>
            req.headers[CORRELATION_ID_HEADER] ?? uuidv4(),
          setup(cls, req) {
            console.log('calling cls middleware');
            const correlationId = cls.getId();
            cls.set('correlationId', correlationId);
            req.headers[CORRELATION_ID_HEADER] = correlationId;
          },
        },
      }),
    providers: [
      {
        provide: APP_INTERCEPTOR,
        useClass: LoggingInterceptor,
      },
      {
        provide: APP_FILTER,
        useClass: AllExceptionsFilter,
      },
    ],
  })
  export class AppModule {}

```
In main.ts
I use prefix for API version 
```
  app.setGlobalPrefix('api', {
      exclude: [
        {
          path: 'health',
          method: RequestMethod.GET,
        },
      ],
    });

  app.useGlobalPipes(
    new ValidationPipe({
      transform: true,
      whitelist: true,
      validationError: {
        target: false,
        value: false,
      },
    })
  );
  
  app.enableVersioning({
    type: VersioningType.URI,
    defaultVersion: '1',
  });


```
Steps I did :
- Get 404 route without the prefix `/api/v1` => Cls Middleware is not triggered ~ there is no log "calling cls middleware"

But when I use that prefix, I see the log and also the correlationId is set in my exception response :sweat_smile: 
It seems like the `mount: true` does not work like it is supposed to do :thinking:

**Comment by alexphamhp** [comment]
Thanks @Papooch for the quick reply
Yes, I fixed it by using your [mounting the middleware manually](https://github.com/Papooch/nestjs-cls#manually-mounting-the-middleware) 
I put the middleware in my bootstrap function and it worked

I agree that the mounting middleware happens too late in the process when both prefix and versioning are involved 

I'm sorry, what I can public is just that above sample code :sweat_smile:

**Comment by Papooch** [comment]
Thanks for the confirmation, I've added a short note about it to the docs.
