### ISSUE TITLE
Cannot install 

### ISSUE THREAD

**Issue by lastdoctor** [Papooch/nestjs-cls#84]
version 3.5.0
```
➜  tools git:(master) ✗ npm i nestjs-cls   
npm ERR! Cannot read properties of null (reading 'edgesOut')

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lastdoctor/.npm/_logs/2023-08-24T11_21_01_740Z-debug-0.log

```

**Comment by Papooch** [comment]
Hi, I would need more context than that. This looks like a problem with the install process, not the library itself.

**Comment by Papooch** [comment]
@lastdoctor Can you provide more information about this error? If not, I am going to close this as invalid.
