### ISSUE TITLE
Cannot access the docs

### ISSUE THREAD

**Issue by ruankotovich** [Papooch/nestjs-cls#90]
Hello there!

I would like to inform that seems to have an issue regarding the docs for this lib (as of 2023-10-23 18:08 UTC)

https://downforeveryoneorjustme.com/papooch.github.io?proto=https

![image](https://github.com/Papooch/nestjs-cls/assets/22301177/cd31aea1-1364-444e-8dfe-e9bbfd969564)

*Recovered link from*:  https://www.npmjs.com/package/nestjs-cls?activeTab=readme
*Original Url*: https://papooch.github.io/nestjs-cls/

**Comment by Papooch** [comment]
Hi, thanks for the report, but there is nothing in the root of [https://papooch.github.io](https://papooch.github.io), so it shows 404. The sub-path `/nestjs-cls` works for me on [https://papooch.github.io/nestjs-cls/](https://papooch.github.io/nestjs-cls/). This is also confirmed by [another down detector tool](https://www.uptrends.com/tools/is-my-website-down?toolRequestGuid=542e6d75-2b10-45e1-bc45-5fda12e09744). Are you by chance in a region where your ISP could be blocking the `github.io` domain?

If you can't access the website, they're always available in markdown format in the `docs` folder. (e.g. [Quick Start](https://github.com/Papooch/nestjs-cls/blob/main/docs/docs/01_introduction/02_quick-start.md))

**Comment by ruankotovich** [comment]
> Hi, thanks for the report, but there is nothing in the root of https://papooch.github.io, so it shows 404. The sub-path `/nestjs-cls` works for me on https://papooch.github.io/nestjs-cls/. This is also confirmed by [another down detector tool](https://www.uptrends.com/tools/is-my-website-down?toolRequestGuid=542e6d75-2b10-45e1-bc45-5fda12e09744). Are you by chance in a region where your ISP could be blocking the `github.io` domain?
> 
> If you can't access the website, they're always available in markdown format in the `docs` folder. (e.g. [Quick Start](https://github.com/Papooch/nestjs-cls/blob/main/docs/docs/01_introduction/02_quick-start.md))

Thank you for the response!

Well, I don't know (yet) why it isn't working for me

I even tried usinc CURL
![image](https://github.com/Papooch/nestjs-cls/assets/22301177/69d20d68-4359-45d0-9e0e-bb46bc2ee757)

**Comment by ruankotovich** [comment]
I tried using a VPN, Its working now, I am not able to describe why It only works for me through a VPN (Asia), I am currently located in Brazil.

**Comment by ruankotovich** [comment]
![image](https://github.com/Papooch/nestjs-cls/assets/22301177/ea46264f-f4f9-496d-9864-0fb5707f009d)
Working like a charm now, without VPN.
